version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=rarog
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - DB_NAME=rarog
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - SECRET_KEY=secret
    depends_on:
      - mysql
    entrypoint:
      [
        "/app/wait-for.sh",
        "mysql:3306",
        "-t 120",
        "--",
        "/app/start.sh"
      ]
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:
    