# Generated by Django 4.1.3 on 2024-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_media_imageid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
